#+STARTUP: content
#+STARTUP: indent
* 2015-12
** Section A
 Directions : In this section, you will hear 8 short conversations and 2 long
 conversations. At the end of each conversation, one or more questions will be
 asked about what was said. Both the conversation and the questions will be
 spoken only once. After each question there will be a pause. During the pause,
 you must read the four choices marked A., B., C. and. D., and decide which is
 the best answer. Thenmark the eorresponding letter on Answer Sheet 1 with a
 single line through the centre.

- 00:00:51
 1. A. The restaurant offers some specials each day.
 B. The restaurant is known for its food varieties.
 C. The dressing makes the mixed salad very inviting.
 D. The woman should mix the ingredients thoroughly.
- 00:01:20
 2. A. He took over the firm from Mary.C. He failed to foresee major problems.
 B. He is running a successful business.D. He is opening a new consulting firm.
 3. A. Someone should be put in charge of office supplies.
 B. The man can leave the discs in the office cabinet.
 C. The man may find the supplies in the cabinet.
 D. The printer in the office has run out of paper.
 4.A. He has to use a magnifying glass to see clearly.
 B. The woman can use his glasses to read.
 C. He has the dictionary the woman wants.
 D. The dictionary is not of much help to him.
 5.A. Redecorating her office.
 B. Majoring in interior design.
 C. Seeking professional advice.
 D. Adding some office furniture.
 6.A. Problems in port management.
 B. Improvement of port facilities.
 C. Delayed shipment of goods.
 D. Shortage of container ships.
 7.A. Their boss.
 B. A colleague.
 C. Their workload.
 D. A coffee machine.
 8.A. Call the hotel manager for help.
 B. Postpone the event until a later date.
 C. Hold the banquet at a different place.
 D. Get an expert to correct the error.

 Questions 9 to 11 are based on the conversation you have just heard.
 9.A. He shares some of the household duties.
 B. He often goes back home late for dinner.
 C. He cooks dinner for the family occasionally.
 D. He dines out from time to time with friends.
 10.A. To take him to dinner.
 B. To talk about a budget plan.
 C. To discuss an urgent problem.
 D. To pass on an important message.
 11. A. Foreign investors are losing confidence in India's economy.
 B. Many multinational enterprises are withdrawing from India.
 C. There are wild fluctuations in the international money market.
 D. There is a sharp increase in India's balance of payment deficit.

 Questions 12 to 15 are based on the conversation you have just heard.
 12. A. They have unrealistic expectations about the other half.
 B. They may not be prepared for a lifelong relationship.
 C. They form a more realistic picture of life.
 D. They try to adapt to their changing roles.
 13. A. He is lucky to have visited many exotic places.
 B. He is able to forget all the troubles in his life.
 C. He is able to meet many interesting people.
 D. He is lucky to be able to do what he loves.
 14.A. It is stressful.
 B. It is full of tim.
 C. It is all glamour.
 D. It is challenging
 15. A. Bothered.
 B. Amazed.
 C. Puzzled.
 D. Excited.

** Section B
 　　Directions : In this section, you will hear 3 short passages. At the end of each passage, you will hear some questions. Both the passage and the questions will be spoken only once. After you hear a question, you must choose the best answer from the four choices marked A., B.,C. and D . Then mark the corresponding letter on Answer Sheet I with a single line through the centre.

 Passage One
 Questions 16 to 18 are based on the passage you have just heard.
 16. A. Maintain the traditional organizational culture.
 B. Learn new ways of relating and working together.
 C. Follow closely the fast development of technology.
 D. Learn to be respectful in a hierarchical organization.
 17. A. How the team integrates with what it is supposed to serve.
 B. How the team is built to keep improving its performance.
 C. What type of personnel the team should be composed of.
 D. What qualifications team members should be equipped with.
 18. A. A team manager must set very clear and high objectives.
 B. Teams must consist of members from different cultures.
 C. Team members should be knowledgeable and creative.
 D. A team manager should develop a certain set of skills.

 Passage Two
 Questions 19 to 22 are based on the passage you have just heard.
 19. A. It is a platform for sharing ideas on teaching at the University of Illinois.
 B. It was mainly used by scientists and technical people to exchange text.
 C. It started off as a successful program but was unable to last long.
 D. It is a program allowing people to share information on the Web.
 20. A. He visited a number of famous computer scientists.
 B. He met with an entrepreneur named Jim Clark.
 C. He sold a program developed by his friends.
 D. He invested in a leading computer business.
 21.A. They had confidence in his new ideas.
 B. They trusted his computer expertise.
 C. They were very keen on new technology.
 D. They believed in his business connections.

 Passage Three
 Questions 22 to 25 are based on the passage you have just heard.
 22.A. Prestige advertising.
 B. Institutional advertising.
 C. Word of mouth advertising.
 D. Distributing free trial products.
 23.A. To sell a particular product.
 B. To build up their reputation.
 C. To promote a specific service.
 D. To attract high-end consumers.
 24. A. By using the services of large advertising agencies.
 B. By hiring their own professional advertising staff.
 C. By buying media space in leading newspapers.
 D. By creating their own ads and commericais.
 25. A. Decide on what specific means of communication to employ.
 B. Conduct a large-scale survey on customer needs.
 C. Specify the objectives of the campaign in detail.
 D. Pretest alternative ads or commercials in certain regions.

** Section C
 　　Directions: In this section, you will hoar a passage three times. When the passage is read for thofirst time, you should listen carefully for its general idea. When tho passage is read for the second time, you are required to fill in tho blanks with the exact words you have just hoard. Finally, when tho passage is read for the third time, you should chock what you have written.

 　　Extinction is difficult concept to grasp. It is an（26）concept. It's not at all like the killing of individual lifeforms that can be renewedthrough normal processes of reproduction. Nor is it simply（27）numbers. Nor is it damage that can somehow be remedied or for which some substitute can be ound. Nor is it something that simply affects our own generation. Nor is it something that could be remedied by some supernatural power. It is rather an（28）and final act for which there is no remedy  on earth or in heaven. A species once extinct is gone forever. However many generations（29)us in coming centuries, none of them will ever see this species that we extinguish. Not only are we bringing about the extinction of life（30）, we are also making the land and the air and the sea so toxic that the very conditions of life are being destroyed.（31）basic natural resources, not only are the nonrenewable resources being（32）in a frenzy ( 疯狂) of processing,consuming, and（33）, but we are also mining much of our renewable resources, such as the very soil itself on which terrestrial (地球上的) life depends.
 　　The change that is taking place on the earth and in our minds is one of the greatest changes ever to take place in human affairs, perhaps the greatest, since what we are talking about is not simply another historical change or cultural（34）, but a change of geological and biological as well as psychological order of（35)。

** 参考答案：

 　　1．C.。未听先知:选项中 restaurant 出现了两次，A.“饭店每天都有特别供应”、
 B.“饭店以食品多样而闻名”和 C.“拌沙拉的调料使这道菜十分诱人”都在描述饭店好的
 一面，故推测本题考查内容与饭店哪方面比较出色有关，而 D.“女士应该将原料进行充分
 搅拌”与其他三个选项内容明显不属于一类，故基本可以提前排除。详解女士发现这家饭
 店的沙拉多种多样，请男士给她推荐点特别的，男士向她推荐了混拌沙拉，因为这道菜的
 调料是用浆果制作而成。由此可知，是特殊的调料使得这款沙拉与众不同。

 　　2．B.。未听先知：四个选项均以 He 开头，由 A.“他从 Mary 那里接手公司”、B.“他正在经营很成功的生意”和 D.“他正在建立一家新的咨询公司”可以猜测，对话内容与男士经营公司有关，C.“他没能预见到一些重大问题”属于男士失败的原因，而其他三个选项均为描述一般事实的陈述句，故基本可以提前排除 C。
 　　详解：女士说她前几天碰到了 Mary，从 Mary 那里听说男士的新咨询公司现在很成功，男士说他的生意发展得比他们预想得要好，现在已经有多于两百名客户了。由此可知，目前男士的生意相当成功。
 　　3．C.。未听先知:选项中出现了 supplies 一词，A.“应该安排人员专门负责办公用品”、B.“男士可以把光盘放在公司的柜子里”、C.“男士应该能在柜子里找到办公用品”和 D.“办公室的打印机没纸了”四个选项的语义相互交错，围绕着办公用品、光盘、纸张、柜子展开，听对话时应注意捕捉这几者之间的相互联系。
 　　详解：对话中男士问女士是否知道光盘和打印纸放在哪儿了，女士说如果还有的话，应该都放在柜子里了，因为所有的办公用品都放在那里。由此可知，女士的意思是男士应该能在柜子里找到他所需要的办公用品。
 　　4．A。未读先知：由四个选项中的 glass(es)和 dictionary 可以判断对话内容与阅读词典和眼镜有关，结合 A“他必须用放大镜才能看清楚”和 B.“女士可以用他的眼镜来阅读”两个选项的意思可以大致判断，对话中的两个人需要借助某种工具才能进行阅读，而 C 和 D.两个选项可以说明他们看不清楚的可能是词典的内容。
 　　详解：对话中女士对男士说词典里的字太小了，她根本就看不清楚那些释义，男士说他要去拿放大镜，没有放大镜，他也无法看清楚。由此可知，男士得用放大镜才能看清楚。
 　　5．A。未听先知：选项均为以 v-ing 形式开头构成的名词性短语，由 A.“重新装修她的办公室”和 D.“为办公室增加点家具”可以推断，对话内容与办公室的家具和装修有关；B.“主修室内装修专业”和 C.“寻找专业建议”也与之相关，由 A.中的 her 判定，听录音时需要特别关注与女士有关的信息。
 　　详解：女士对男士说她正考虑重新装修办公室，家具旧了，墙上的漆也开始脱落了，男士说他可以把他弟妹的电话给女士，因为他弟妹毕业于室内装修学院，可以给女士免费进行评估。由此可知，女士正在考虑的事情是重新装修办公室。
 　　6．D.。未听先知：四个选项均为名词性短语，由选项 A.“港口管理问题”、B.“港口设施的改善”、C.“货运物品延期”和 D.“集装箱船匮乏”可以看出，这些选项都提到了港口所面临的一些问题，因此听对话时对此类信息要特别关注。
 　　详解：对话中女士对男士说她们有一大批货物需要运走，但怎么也找不到集装箱船只，男士表示在这个港口，此类问题一直存在，港口的设施根本满足不了人们的需求。由此可知，两人讨论的是港口缺乏集装箱船只的问题。
 　　7．B.。未听先知：四个选项都很简短，为四个名词短语，且内容各不相同，通常出现此类选项时，考查内容一般围绕对话的主旨大意展开。
 　　详解：对话中女士奇怪为什么 Rod 没有涨工资，男士说那是因为老板觉得他的工作态度有问题，老板说她看到 Rob 在咖啡机边的时间比在办公桌前办公的时间还要多。由此可知，对话中的两人正在讨论他们的同事 Rod。
 　　8．C.。未听先知：四个选项均为动词短语，可以推断本题考查的是某人的动作行为，结合选项 A.“向酒店经理打电话求助”、B.“把事项日期延后”、C.“换个地方举办宴会”和 D.“请专家来改正问题”可以推断，应该是某件事情出了差错或是变故，因此本题考查的内容与人们采取的应对措施有关。
 　　详解：对话中女士对男士说酒店打来电话，说由于日程安排出了问题，他们不能承接宴会了，男士马上说他知道在 High Street 有一家印度餐馆，可以为团体客户提供特殊待遇，那里的食物很棒，房间也足够大。由此可知，男士的言外之意是说他们可以把宴会的地点改在他所推荐的印度餐馆。

 　　9．What do we learn about the man’s daily life?
 　　B.。详解：四个选项均以 He 开头，且均使用了一般现在时，可以推测本题考查内容与男士的日常生活有关。由各选项 A.“他分担一些家务职责”、B.“他经常回家很晚，赶不上吃晚饭”、C.“他偶尔会为家人做饭”和 D.“他有时会与朋友外出就餐”可以看出，本题的重点是男士通常是怎样解决晚餐的。其中，A.与其他三个选项的内容有较大差异，可以提前排除。对话中男士与女士见面时，男士告诉女士他正要回家，Susan 正在家里等他回去吃晚餐，他不能总像平日里那样老是赶不上吃晚餐。for a change 表达的意思是“改变一下”，既然男士今天要按时回家与家人一起共进晚餐，也就可以推测出他大多数时候是不按时回家吃晚餐的。
 　　10．Why did the woman come to see the man?
 　　D.。详解：四个选项均为动词不定式结构，此类选项通常表示本题考查的内容为即将发生的行为动作或某种动作的目的，A.“带他去吃晚餐”与 B.“谈论一项预算计划”、C.“讨论一个紧急问题”以及 D.“告知一个重要信息”这三个选项的内容明显不属于一类，可以预先排除。对话中女士说她很抱歉在周五的这个时间来找男士，但她的事情非常重要，而没有提到“问题”，因此排除 C.，显然女士来找男士的目的就是要告诉男士一件重要的事情。
 　　11．What makes the woman worry about the Indian Rupee?
 　　D.。详解：四个选项都与商业行为相关，而且两次提到了 India，可以判断对话内容涉及印度的商业或经济，选项均为对印度经济进行负面描述的句子，但内容各不相同，无法进行排除或断定本题所考查的重点，听对话时就需要对所有涉及到印度经济的内容多加留意。对话中女士明确告诉男士印度的收支平衡赤字急剧升高。

 　　12．What does the mail say about most people when they get into love affairs?
 　　A.。详解：四个选项均以 They 开头，根据选项 A.“他们对自己的另一半有着不切实际的期待”、B.“他们或许没有准备好形成一种相伴一生的关系”、C.“他们对生活有了更为现实的认识”和 D.“他们想要适应自己角色的转变”可以判断，选项中的 they 指的就是普通大众，本题考查的是人们对爱情或者婚姻、家庭的看法。对话中女士问男士为什么爱情不能永葆活力，男士说人们陷入恋爱关系时，往往都对对方抱有一种不切实际的期待，如果对方与自己想象得不一样，则希望对方能够为自己而改变．坦实际上，人们很难真正改变。
 　　13．What does the mail say about himself as a singer OH the road most of his life?
 　　D.。详解：四个选项均以 He 开头，A.“他很幸运，能够去很多新奇的地方”、B.“他能够忘记生活中的烦恼”、C.“他能够认识很多有趣的人”和 D.“他很幸运，能够做自己喜欢的事情”，四个选项都是在描述男士的美好生活，可以判断对话中一定讲述了男士幸福的一面，听对话时对此类信息要特别注意。对话中女士问男士，他已经 62 岁了，还经常到处走动，是什么吸引他一直上路，男士毫不犹豫地说是音乐促使他前行，能够做自己真正热爱的事情的人是幸运的，他们能够触碰到生活的极致。由此可见，男士所做的正是他自己喜欢的事情。
 　　14．What do most people think of the life of a famous musician?
 　　C.。详解：四个选项均为简单的主系表结构，四个形容词是关键，选项所给信息过少，无法判断本题考查内容，但听录音时，对与这些形容词有关联的内容都要注意捕捉。对话中女士问男士人们最容易对知名音乐家所产生的错误概念是什么，男士明确地说，人们认为知名音乐家的生活只有光辉，这是不对的。生活对于他们并不比对待普通人更加仁慈。
 　　15．How does the mall feel whenever he is recognized by his fans?
 　　B.。详解：四个选项均为单个形容词，有正面的，也有负面的，选项所给信息过少，无法判断本题考查内容，但听录音时，对与这些形容词有关联的内容都要注意捕捉。对话中女士问男士走到哪儿都会被人认出来的感觉如何，男士说，按说他应该已经习惯了这种感觉，但事实是，他依然感觉十分惊异。他举了一个例子，他曾经去过一个日本小镇，那里的人根本不会说英语，但却一下子就认出他了，还知道他的音乐。fascinating 和 amazed 的意思相似，都表示“惊异，惊喜”。

 　　16．What should team members do to fully realize their potential?’
 　　B.。详解：四个选项均为以动词原形开头的句子结构，可以判断本题考查的是行为动作。A.“保持传统的组织文化”、B.“学习新的关联方式，共同协作”、C.“紧跟技术的快速发展”和 D.“学会尊重企业等级制度”均为现代企业中员工所应该做的事情，听录音时注意判断文章当中提到的是哪一点。短文中说，虽然团队当中可能有些人的确非常博学，但他们也应该学会与团队中的其他人员共同协作，形成良好的合作关系，一起解决问题。
 　　17．What needs to be considered for effective team management?
 　　A.。详解：四个选项均为疑问词开头的陈述句语序的句子，因此可以判断问题中一定包含某种结构，这些选项均可以充当该词或该表达的宾语。结合选项 A.“团队该怎样与它的服务对象相融合”、B.“该怎样建设团队才能改善团队表现”、C.”团队中应该纳入什么样的员工”和 D.“团队中的成员应该具有怎样的素质”可以推测，本题考查应该怎样进行团队建设。短文中提到，问题不仅在于应该怎样让团队更高效地工作，还应该让团队与他所服务的公司或社会融合在一起。
 　　18．What conclusion Can we draw from what Casey says?
 　　D.。详解：四个选项的意思分别为 A.“团队经理必须设立清晰且较高的目标”、B.“团队必须包含有不同文化背景的队员”、C.“团队成员应该知识丰富，并富有创造性”和 D.“团队经理应该具备某些特定的技能”，其中有两项都提到了团队经理，可以初步判断本题考查的内容极有可能与团队经理所应该具备的素质或是其所应该承担的责任有关。短文中提到按照 Casey 的看法，如果团队经理能够展示出他所提到的各种素质，整个团队就能够更好地发挥潜力，实现目标。也就是说，团队经理应该具备某些特定的素质。

 　　19．Wath do we learn about Mosaic?
 　　D.。详解：四个选项均以 It 开头，意思分别为 A.“它是 Illinois 大学提供的分享教学观点的平台”
 　　B.“它主要用于科学家和技术人员之间的文字信息传递”、C.“它刚开始时是一个很成功的软件，但没能持续很久”和 D.“这一程序允许人们通过网络共享信息”，由此可以判断，It 一定是某种技术形式，更有可能是某种软件或平台，本题考查内容与 It 的功能有关。短文一开始就提到，Mark 和他的朋友开发了 Mosaic，它可以允许人们通过网络在全世界范围内共享信息。
 　　20．What did Andreessen do upon arriving in Silicon Valley?
 　　B.。详解：选项均以 He 开头，A.“他拜访了一批著名的计算机科学家”、B.“他与一位名为 Jim Clark 的企业家碰了面”、C.“他卖掉了朋友们开发的软件”和 D.“他投资了一项领先的计算机生意”都是对 He 行为动作的描述，听录音时应注意捕捉与 He 的行为动作相关的信息。短文中说 Andreessen 一到硅谷，首先就与硅谷的著名企业家 Jim Clark 进行了会面。
 　　21．Why were venture capitalists willing to join in Clark’s investment?
 　　A.。详解：四个选项均以 They 开头，A.“他们对他的新想法充满信心”、B.“他们相信他的计算机专业知识”、C.“他们对新科技十分狂热”、D.“他们相信他的业务关系”都是在表述“他们”对于“他”的看法．听录音时首先要确定的是 They 和 he 分别指代的是什么人，才能正确判断他们之间的关联。短文最后一部分说，Clark 不仅自己投了资，还为 Andreessen 找了风险投资家，他们之所以愿意为 Andreessen 投资，主要是因为他们热衷于 Clark 的新想法。

 　　22．What is probably the best form of advertising according to the speaker?
 　　C.。详解：选项均为名词短语，A.、B.、C.三个选项描述的都是广告类型，D.虽然没有出现 advertising 一词，但“分发免费试用品”也是广告推销的一种形式，可以判定本题考查内容与广告形式有关。短文开头处提到，最好的广告形式就是臼口相传，也就是人们会把自己认为不错的产品或服务推荐给朋友。
 　　23．What does the speaker say is purpose of many organizations’using prestige advertising?
 　　B.。详解：选项均为不定式短语，通常不定式短语所表达的是目的、打算或是即将发生的行为动作，由各选项意思：A.“销售特定商品”、B.“树立声誉”、C.“推广特定服务”和 D.“吸引高端客户”可以推测，本题考查内容与广告的目的有关。短文中提到很多机构通过广告公司进行宣传，并不一定是想要销售产品，更多的是想树立企业或公司的良好声誉。
 　　24．How do large companies generally handle their advertising?
 　　A.。详解：四个选项均为以 By 开头的介词短语，介词 by 通常表示某种方式或手段，由各选项的意思：
 　　A.“使用大型广告公司的服务”、B.“雇用自己的专业广告人员”、C.“在行业领先的报纸上购买广告空间”和 D.“制作自己的广告”可知，本题考查的是通过何种手段进行广告活动。短文中提到，虽然对于大公司来说，建立自己的广告部门、自己撰写广告方案、购买媒体空间都不是多么困难的事情，但他们还是倾向于借助大型广告公司所提供的服务来做广告。
 　　25．What would advertising agencies often do before a national campaign?
 　　D.。详解：四个选项均为动词原形开头的句子结构，可以判定本题考查的是行为动作，由 B.选项中的 survey 和 D.选项中的 Pre．test，ads 可以推测，本题考查内容与真正投放广告前的行为有关。短文最后提到，广告公司在向全国投放广告之前，通常会先小范围地在报纸、电视等渠道上进行测试，也就是说，他们会在特定的地区进行广告试验。

 　　26．eternal。详解：空格位于不定冠词 an 和名词 concept 之间，应该填入以元音发音开头的形容词作定语，修饰名词 concept。第一句提到物种灭绝是一个不容易理解的概念，而在下文提到，它与杀死那些可以再重生的单个生命形式不同，也就是说，　　它是一个永远无法逆转的概念。eternal 意为“永远的，永恒的”。
 　　27．diminishing。详解：空格所在句和后面两句构成了排比句式，说明了 extinction 这一概念的独特性。空格所在句为倒装句，充当句子的表语，由于空格后有名词，因此，填入的词需要和名词 numbers 一起构成名词性短语。由句意可知，灭绝不仅仅是数字的减少。diminish 意为“减少，减小”。
 　　28．absolute。详解：空格位于连词 and 之前，需要填入一个形容词，与 final 形成并列关系，一起来修饰名词 act。物种的灭绝是永远的消失，绝对不会再出现。absolute 意为“绝对的”。
 　　29．succeed。详解：空格位于状语从句中的谓语部分，由于前面的主语为复数，主句时态为一般将来时，因此，空格内填人动词的一般现在时。由空格后的 in coming centuries 可知，此处要表达的意思是：不管在我们之后还有多少代人会继续生存，都不会再看到那些已经灭绝的物种了。succeed 意为“接替，继承”。
 　　30．on a vast scale。详解：空格所在句不缺少句子主要成分，因此，应填入副词或副词短语，充当句子的状语。上一段提到了灭绝，本段提到了人类对自然资源的浪费和破坏，这些都是大范围的行为。on a vast scale 意为“大面积的，大范围的”。
 　　31．As regards。详解：空格与其后的名词短语 basic natural resources 不是句子主干的一部分，因此需要填人介词，构成介词短语。上一句说到了人类对天空、大地和空气的污染，本句则提到了自然资源。As regards 意为“至于，关于”。注意空格位于句首，As 首字母需要大写。
 　　32．used up。详解：空格位于句子的谓语部分，与 are…being 连在一起构成现在进行时的被动语态，表示“正在被……”，因此应该填入动词或动词词组。由 but we are also rtfinin9 可知，此处要表达的意思是：我们正在以疯狂的速度和手段将自然界中不可再生的资源消耗殆尽。used up 意为“用光，消耗光”。注意使用动词的过去分词形式。
 　　33．disposing。详解：空格前有两个动名词 processing，consuming，由 and 确认这三个词应该是并列关系，因此也填入动词的一 ing 形式。这里要表达的意思是：人类正在处理、消耗、丢弃珍贵的资源。disposing 意为“处理，扔掉”。
 　　34．modification。详解：空格位于形容词 cultural 之后，应该填入名词，与 cultural 形成名词短语后，再通过 OI?与 historical change 形成并列关系。与 change“变化”相对应的词为 modification。modification 意为“修改，改变”。
 　　35．magnitude。详解：空格位于介词 0f 之后，应该填入名词，充当介词的宾语。空格所在句要表达的意思是：人类正在经历的变革十分重大，不仅是简单的历史变迁或是文化变更，而是地理、生物以及心理等各种秩序的重大变革。magnitude 意为“重要性。重要程度”。

** 原文
*** 短对话
1.W: Wow, what variety of salads you've got on your menu! Could you recommend
something special?

M: Well, I think you can try this mixed salad. We make the dressing with fresh
berries.

Q: What does the man mean?

2.W: I was talking to Mary the other day and she mentioned that your new consulting firm is doing really well.

M: Yes, business picked up much faster than we anticipated. We now have over 200 clients.

Q: What do we learn about the man from the conversation?

3.M: Do you know where we keep flash discs and printing paper?

W: They should be in the cabinet if there are any. That's where we keep all of our office supplies.

Q: What does the woman mean?

4.W: The print in this dictionary is so small. I can't read the explanations at all.

M: Let me get my magnifying glass. I know I just can't do without it.

Q: What does the man mean?

5.W: I'm considering having my office redecorated. The furniture is old and the paint is chipping.

M: I'll give you my sister-in-law's number. She just graduated from an interior design academy and will give a free estimate.

Q: What is the woman considering?

6.W: We have a full load of goods that needs to be delivered. But we can't get a container ship anywhere.

M: That's always been a problem in this port. The facilities here are never able to meet our needs.

Q: What are the speakers talking about?

7.W: Why didn't Rod get a pay raise?

M: The boss just isn't convinced that his work attitude warranted. She said she saw him by the coffee machine more often than at his desk.

Q: What are the speakers talking about?

8.W: The hotel called, saying that because of a scheduling error, they won't be able to cater for our banquet.

M: I know an Indian restaurant on the High Street that offers a special dinner for groups. The food is excellent and the room is large enough to accommodate us.

Q: What does the man suggest they do?

*** 长对话

Conversation 1

M: Hello Jane.

W: Hello Paul.

M: Please coming. I'm just getting ready to go home. Susan is expectingme for dinner. I wanted to be on time for a change.

W: Look, I'm terribly sorry to drop in this time on Friday, Paul, butit is rather important.

M: That's OK. What's the problem?

W: Well, Paul, I won't keep you long. You see there is a problem withthe exchange rates. The Indian Rupee has taken a fall on the foreign exchangemarket. You see there is being a sharp increase in Indian's balance of paymentdeficit.

M: I see. How serious, isn't it?

W: Well, as you know, there have been reports of unrest India, and theprospects for the Rupee look pretty gloomy.

M: And that's going to affect us, as if we didn't have enough problemson our hands.

W: So I thought it would be wise to take out forward exchange cover toprotect our position on the outstanding contract.

M: Just a minute. Forward exchange cover, now what does that meanexactly?

W: Well, it means that JO notes enters into a commitment to sell IndianRupees at the present rate.

M: I see. And how will that benefit us?

W: Well, JO notes wouldn't lose out if Indian Rupee falls further.

M: What will it cost, Jane?

W: A small percentage, about 1% and that can be built into the price ofthe bike.

M: Well, I don't suppose there is much choice. All right Jane, let'sput it into action.

Q9: What do we learn aboutthe man's daily life?

Q10: Why did the woman cometo see the man?

Q11: What makes the womanworry about the Indian Rupee?

Conversation 2

W: Charles, among other things, you regarded as one of the America'sgreat masters of the blues. A musical idiom does essentially about loss,particularly the loss of romantic love. Why does love die?

M: People often get into love affairs because they have unrealisticexpectations about somebody. Then when the person doesn't turn out to be whothey thought he or she was, they start thinking maybe I can change him or her.That kind of thinking is a mistake. Because when the dust settles, people aregoing to be pretty much what they are. It's a rare thing for anybody to be ableto change who they really are. And this creates a lot of problems.

W: At 62, you continue to spend a large percentage of your lifetouring. What appeals to you about life on the road?

M: Music, I don't especially love life on the road, but I figure if youare lucky enough to be able to do what you truly love doing, you've got theultimate of life.

W: What's the most widely-held misconception about the life of a famousmusician?

M: People think it's all glamour. Actually we have the same troublesthey do. Playing music doesn't mean life treats you any better.

W: How do you feel about being recognized everywhere you go?

M: You think I be used to it by now. But I still find it fascinating.You go to a little town in Japan, where nobody speaks English, yet they knowyou on side and know all your music. I'm still amazed by the love peopleexpress for me and by music.

Q12: What does the man sayabout most people when they get into love affairs?

Q13: What does the man sayabout himself as a singer on the road most of his life?

Q14: What do most peoplethink of the life of a famous musician?

Q15: How does the man feelwhenever he was recognized by his fans?

*** 短文

Passage 1

Changing technology and markets have stimulated the team approach tomanagement. Inflation, resource scarcity, reduced personnel levels and budgetcuts have all underscore the need for better coordination in organizations.Team management provides for this coordination. Team management calls for newskills if personnel potential is to be fully realized. Although a team may be composed ofknowledgeable people, they must learn new ways of relating and working togetherto solve cross-functional problems. When teams consist to be experiencedemployees from hierarchical organizations, who have been condition totraditional organizational culture. Cooperation may not occur naturally, itmainly to be created. Furthermore, the issue is not just how the team canfunction more effectively, but how it integrates with the overall organization,all society that it supposes it serves. A group of individuals is notautomatically a team. Therefore, team building may be necessary in order toimprove the group's performance. Casey, an expert in this field, suggests thatthe cooperation process within teams must be organized, promoted and managed.He believes the team corporation results when members go beyond theirindividual capabilities, beyond what each is used to being and doing. Together,the team may then produce something new, unique and superior to that of any onemember. For this to happen, he suggests the multi-cultural managers exhibitunderstanding of their own and others' cultural influences and limitations.They should also cultivate such skills as toleration of ambiguity, persistenceand patience, as well as assertedness. If a team manager exemplifies suchqualities, then the team as a whole would be better able to realize theirpotential and achieve their objectives.

Q16: What should teammembers do to fully realize their potential?

Q17: What needs to beconsidered for effective team management?

Q18: What conclusion can wedraw from what Casey says?

Passage 2

In early 1994, when MarkAndreessen was just 23 years old, he arrived in Silicon Valley with an ideathat would change the world. As a student at the University of Illinois, he andhis friends had developed a program called Mosaic, which allowed people toshare information on the worldwide web. Before Mosaic, the web had been usedmainly by scientists and other technical people, who were happy just to sendand receive text. But with Mosaic, Andreessen and his friends had developed aprogram, which could send images over the web as well. Mosaic was an overnightsuccess. It was put on the university's network at the beginning of 1993. Andby the end of the year, it had over a million users. Soon after, Andreessenwent to seek his fortune in Silicon Valley. Once he got there, he started tohave meetings with a man called Jim Clark, who was one of the Valley's mostfamous entrepreneurs. In 1994, nobody was making any real money from theInternet, which was still very slow and hard to use. But Andreessen had seen an opportunity thatwould make him and Clark rich within two years. He suggested they should createa new computer program that would do the same job as Mosaic but would be mucheasier to use. Clark listened carefully to Andreessen, whose ideas andenthusiasm impressed him greatly. Eventually, Clark agreed to invest threemillion dollars of his own money in the project, and to raise an extra fifteenmillion from venture capitalists, who were always keen to listen to Clark's newideas.

Q19：What do we learn about Mosaic?

Q20：What did Andreessen do upon arriving in Silicon Valley?

Q21：Why were venture capitalists willing to join in Clark'sinvestment?

Passage 3

Advertising informs consumers about the existence and benefits ofproducts and services and attempts to persuade them to buy them. The best formof advertising is probably word of mouth advertising which occurs when peopletell their friends about the benefits of products or services that they havepurchased. Yet virtually no providers of goods or services relay on this alone,which using paid advertising instead. Indeed many organizations also use institutionalor prestige advertising which is designed to build up their reputation ratherthan to sell particular products. Although large companies could easily set up theirown advertising departments, write their own advertisements and by media space themselves.They tend to use the services of large advertising agencies. These are likelyto have more resources and more knowledge about all aspects of advertising andadvertising media than single company. It is also easier for a dissatisfycompany to give its account to another agency. And it would be to fire theirown advertising staff. The company generally give the advertising agency andagreed budget. A statement of the objective of the advertising campaign know asbrief and overall advertising strategy concerning the message to becommunicated to the target customers. The agency creates advertisements anddevelops a media prime, specifying which media will be used and in which proportions.Agencies often produce alternative ads or commercials that pretested innewspapers, television stations etc. in different parts of the country. Beforea final choices was made

prior to anational campaign.

Q22：What is probably the bestform of advertising according to the speaker?

Q23：What does the speaker sayis the proposes of many organization using prestige advertising ?

Q24：How did large companiesgenerally handle their advertising?

Q25：What would advertisingagencies often do before a national campaign?

*** 听写题

Extinction is a difficult concept to grasp. It is an eternal concept. It is not at all like the killing of individual life forms that can be renewedthrough normal processes of reproduction. Nor is simply diminishing numbers.Nor is it damage that can somehow be remedied or for which some substitute canbe found. Nor is it something that only affects our own generation. Nor is it somethingthat could be remedied by some supernatural power. It is, rather, an absoluteand final act which there is no remedy on earth or in heaven. A species onceextinct, it's gone forever. However many generations succeed us in comingcenturies, none of them will ever see this species that we extinguish. Not onlyus we bring about extinction of life on a vast scale. We are also making theland and the air and sea so toxic that the very conditions of life are being destroyed.As regard natural resources ,not only are the none renewable resources beingused up in a of frenzy of processing, consuming and disposing but we are alsoruining much of our renewable resources. Such as the very solid self on which terrestriallife depends. The change that is taking place on the earth and in our minds isone of the greatest changes ever to take place in human affairs. Perhaps thegreatest, since we are talking about is not simply another historical change orcultural modification. But it change the geological and biological as well as psychologicalorder of magnitude.
