* Lee
** consonant-consonant
*** 失爆
- [t][k][p][d][g][b]+与其不相同的辅音时，只阻塞气流不将之释放，只做口型不送气。
*** 击穿
- [h]
- 前一个单词以辅音结尾，后一个以 h 发音开头时，字母 h 不再发音。
*** 叠合
- 前一个单词以辅音结尾，后一个单词以相同音节的辅音开头。
** consonant-vowel
*** [r]+vowel
*** [l]+vowel
*** [n]+vowel
*** [t]+vowel
- [t] -> [d]
** vowel-vowel
*** [əu][au][u][u:]+vowel
- 连接时加上半元音[w]
*** [ei][ai][ɔi][i][i:]+vowel
- 连接时加上半元音[j]
*** [t]+[j]
- [t]+[j] -> [tʃ]
*** [d]+[j]
- [d]+[j] -> [dʒ]
*** [s]+[j]
- [s]+[j] -> [ʃ]
* Qzone
考研复试英文材料（赛领独家整理）
这是去年部分考取 985、211 同学的复试材料。均为我的学生。材料是他们写好，我修改、润色的。希望对本届考研同学有帮助。如果你觉得你分数能进入复试，也可以把写好的英文材料发我邮箱（2443744343@qq.com），邮件主题：考研复试+姓名+专业+报考院校+本科院校+QQ。我抽时间润色。再接再厉，加油！
(1)
Good morning, dear professors.

My name is __. I come from HENAN Province, where many ancient citieslike Luoyang, Kaifeng and my hometown ___ lie.  I will graduate from ____ this July when I am 21years old.

In our class committee, I have been in charge of study for the lastthree years. With a strong sense of responsibility, I always work earnestly andcommunicate effectively between the teachers and my classmates, which hasenabled me to win the award of excellent service in our school.

In terms of hobbies, I love __ the best  I havebenefited a lot from it, as itnot only enables me to keep fit but helps me relax from heavy stressduring the time when I have been preparing the postgraduate entrance exam. Andluckily, I make it and now I am here to introduce myself to you, distinguishedprofessors of my dream university. Apart from ____, I enjoy listening toEnglish songs such as HERO by Maria Carey, which always cheer me up when I am inlow spirits. I also like watching English movies and programs such as PrisonBreak, the Gossip girl and so on. By doing so, not only have I learned a lotabout personality, I have also enhanced my English proficiency. I have passedthe CET4&CET6 with a scoreof 518 and 538 respectively .

The major I hope to pursue for my further education is __. I havelearned and mastered some basic theories and practice skills concerning mymajor, however, it is far from enough. Faced with a rapidly changing marketenvironment, so many  enterprises may getstuck in a dilemma of transformation. I hope I can become an outgoing talent, devotingmyself to conducting useful research in this field, and make contributions toour society.

Since I was in senior high, I have heard of your renowned universityand dreamed of furthering my education here. If i am lucky enough to get thischance, I believe that, through concret actions, I will prove to be aconstructive asset.

Thank you!

(2)

Dear professors, good morning!

I am honored and excited to be here for this interview. My name is ___.Icome from ___, ___ province. Next July, I will graduate from ___ university, majoringin ____.

I am an easy-going boy. That’s the reason why I enjoy a goodrelationship with my classmates. Besides, I am hard-working, especially when I dothings I am really interested in. I will try my best to finish it no matter howdifficult it is. (for example, I love running. During the days when I preparedfor the postgraduate entrance examination, I insisted on running every day nomatter what the weather was like.)What’s more, I am full of curiosity, eager tolearn new things and receive new challenges.

In terms of hobbies, I like reading（My favorite is the romance of Three kingdoms, because it includeslots of knowledge about management, and I have learned much from the book）, running, listening to the music, playing tennis. What’s more, Ilike English very much. That’s why I have kept a habit of writing English diaryon a regular basis. No Pains, No gains. I have passed CET6 with ease and got ahigh score on English in the entrance examination.

I hope to study further as a postgraduate. I believe that one willeasily lag behind unless he keeps on learning. I want to strive for the better,and this is why I come here today. Your distinguished university is my best andfirst choice. I have been fascinated by the excellent academic atmosphere inyour  university since I first visited ittwo years ago.

That’s all. Thank you very much.

(3)

Goodmorning, dear professors.

I am greatly honoredand excited to be here for this interview.

Please let meintroduce myself briefly. My name is ___. I am ___ years old. I come from asmall village of __, ___ province, which filled my childhood with pleasure anddreams.

I have finished myundergraduate education in ___ university, majoring in logistics management.When I was a junior, I had a lesson called financial management. By learningit, I get to know some basic knowledge which I did not understand previously. Imust admit that this kind of knowledge fascinates me. Therefore, I am eager tolearn more about economics and I hope I can further my study in yourprestigious university.

As a proverb goes,“one reaps what he sows.” I often tell myself, “Study harder, and you will makeit, because nothing is impossible to a willing heart.” It is indeed possible tocreate miracles by relying on tireless efforts.

In terms of hobbies, Ilove reading. I like reading some classics written by Dale Carnegie. Inaddition, I like watching movies. My favorite one is The Shawshank Redemption,which lets me know that one’s hope is the best of things. So everything I do, Ido it with love and passion.

If I am given a chanceto study in your university, I will spare no efforts to learn and achieve myself-value.

That’s all about me. Thanksfor your attention.

(4)

Good morning, dear professors.

It`s really nice to behere for the interview. In fact, to me, it`s more like a dream to be here inthe best university. I feel extremely happy and honored.

My name is ___. Iam...years old, and I come from ___, ___ Province, a beautiful place. ThisJuly, I will graduate from the school of___, ___ University, majoring in ____.

During my collegeyears, I have been studying hard. As a result, I have obtained scholarshipseveral times. Meanwhile, I am the undersecretary of ____ University’s InternetCultural Studio. In addition, I actively involve myself in public welfareprograms and have been awarded “Excellent Student Leader” and “OutstandingYouth Volunteer” respectively by ___ University. I am very proud of that.

As you know,ChaiJing’s Under the Dome, a documentary on smog, has aroused great concernsnationwide. Smog has become the most dreadful weather in people`s eyes. From myperspective, instead of regarding it as a serious environmental problem, I`drather describe it as an urgent problem of energy. Therefore, in mypostgraduate study, I planto devote myself in the direction of material and energy, such asenergy-storage materials, battery and new energy technology. As Premier LiKeqiang said in his government report, “The most formidable tasks demand thegreatest sense of mission（千钧重任惟担当）” I hope I cancontribute my share in the cause of environmental protection. That`s the reasonwhy I choose the direction of new energy.

If I am luckilyadmitted by ___ University, which is my dream, under teachers’ academicinstructions, and classmates’ teamwork, I believe I can give full play to myvalue.

That’s all. Thank you.

(5)



Good afternoon , dear professors.

I am much honored and excited to be herefor this interview.

My name is ___. I am ___ years old . I comefrom ___, ___ province. This July, I'll graduate from ___ university , majoringin ____.

Last winter, I took part in thepostgraduate entrance exams. This is the most encouraging decision that I havemade, meanwhile it also demands the most industrious and earnest efforts.

I believe, the harder I work, the luckier Iam. Therefore, I have always been working hard. One reaps what he sows. Today Ican stand here, and achieve preliminarily what I want owing to my tirelessefforts in pursuing my dream. I dream to study further as a postgraduate,because I love my major and I hope to study it more systematically in ___University, my dream university.

In terms of my character, I am open-minded,active and optimistic. Just as my name indicates, I like smiling. I sincerelyhope that I can make others happy.

That's all about me. Thank you!



Why 考研？

Generally speaking, there are three mainreasons.

Firstly , I want to be a teacher and hope Ideserve a bright future through my efforts. On the other hand, my family havealways encouraged and supported me to strive for the best, and I hope to liveup to their expectations. Most importantly, it’s a dream that I have longcherished. And people who pursue their dreams with tireless efforts are themost charming and lovable ones.



Hometown

luoyang is my hometown. It has a long andsplendid history. It’s well-known home and abroad for Longmen Grottoes and abroad range of peonies. To me, Luoyang is like a cup of tea, deserving a deeptaste. In all, luoyang has a lasting appeal and I love it deeply.



 College

___College, is a college in Henanprovince.  Teachers here are friendly andresponsible, and students are industrious. It is the place where I have laid asolid foundation for the study of my major, Chinese language and literature.It  is also the place where I have made alot of friends. I love my university.



why I choose this major

Chinese language and literature, in myview,  is closely related to people’swise and broad views of life and spiritual level. It plays a leading role inideological, spiritual and political education. Also, it is indispensable tothe spreading of China’s great civilization. So I think I am wise in choosingmy major.





(6)

自我介绍

Good afternoon, dearprofessors!

It’s my great honor tohave this opportunity for an interview. I hope I can make an impressiveperformance.

My name is ____. Icome from ____, ____ Province. Currently, I am a senior student in ____university. In the past three and a half years, I have spent much time onstudy, thereby laying a solid foundation for further study. Not only have I hada good command of economics, management, engineering construction, accountancy,project cost, financial management and so on, I also excel in some softwareslike CAD, Revit, etc. In addition, I have won the third prize in the NationalEnglish Contest for College Student.

Personally, I am apatient and easygoing girl. I always try my best to do my job. I amdetail-oriented, cooperative and creative, and have ability of practice. When I work on aproject, I don't just want to meet deadlines. Rather, I prefer to complete theproject well ahead of schedule.

In terms of hobbies, Ilove drawing the best, not only because it’s a process of creating beauties, but also because it brings me relaxingfeelings. What’s more, it builds on my perseverance and patience.

I am longing for mypostgraduate studies and life. Thank you for giving me such a valuableopportunity! And thanks for your time.



故乡特色，故乡与上海的区别，你更喜欢哪一个，谈谈上海近十年的经济发展

I come from ___, ___ Province,a beautiful city which is famous for ham. And my native place ___is thetownship of medicinal herbs(药材之乡）. Because of itspleasant climate and unique terrain, some rear medicine materials can becultivated. There are eight famous medicinal plants in Zhejiang, named “浙八味”, five of which originate fromPanan.

My hometown issurrounded by mountains, in the middle of the province, so it would be lesswindy than Shanghai. In terms of other aspects of climate, they are alike.Another significant difference is that the life tempo in my hometown is muchslower than that of Shanghai.

If you ask me whichone I prefer, I would say that they both have their charms. My hometown hasfresh air while Shanghai offers fresh experience. My hometown is peaceful andfamiliar, while Shanghai is dynamic and charming. I wish I could enjoydifferent kinds of life.

Shanghai has long beenthe financial center of china. In the latest decade, it has became more andmore international, with the holding of World Expo, the SCO summit and so on.And now with the development of the Shanghai Pilot Free Trade Zone, itseconomic becomes more attractive  allover the world.



谈谈你对未来的规划（职业规划）

There must be manythings to learn if I am enrolled into my ideal research field. If I were luckyenough to be admitted by this prestigious university, I would spent most of mytime on valuation, and I hope I could gain expertise in valuation when Igraduate in two years. Meanwhile, if possible, I wish I could do some part-timejobs about valuation to gain some practical experience.

你为什么选择___大学

I’ve heard that____ ison the top of the list of Chinese financial universities, and a lot ofsuccessful entrepreneurs and executives graduated here. And I firmly believethat if I am lucky enough to be admitted into your university I could equipmyself with professional and advanced expertise about valuation here.



你为什么考研(whydo you take part in the postgraduate entrance exams?)

My undergraduate majoris management engineering, and the courses I’ve learned are comprehensive,including management, engineering, and economics. During the past three yearsand a half, I have learned a lot of professional knowledge and practical skillsregarding my major. However, you know that it offered extensive knowledge but Iwant to be specialized in one certain area. What’s more, further study isactually urgent for me to realize and finally achieve my self-value. In thehighly competitive modern society, everyone is working hard to grasp anyopportunity for self-development, myself included. That’s the reason why Idream to go on with a further education as a postgraduate in your prestigiousuniversity, where I can have an in-depth and systematic study of valuation,broaden my horizon, and enhance my expertise.



你为什么选择资产评估

Valuation is the majorthat I hope to pursue for my further education. Faced with the rapidly changingmarket environment, many national enterprises get stuck in a dilemma oftransformation, and there are more dealings in the market nowadays, which givesrise to huge needs for growing numbers of talents with advanced valuationskills. What’s more, valuation has many things in common with my major. Both ofthem need knowledge about economics, financial management, and sometimesengineering. I hope to become such an outstanding talent, and make contributionto our society.



你的理想是什么

I hope I can be adistinguished CPV(certified public valuer) in the future, and master the skillsof valuation, and I dream to start my own businesses after that, I mean,setting up a company of my own if possible.



你想选择什么样的导师

It would be a greathonor for me to follow any of the tutors in Shanghai university of finance andeconomics, but in consideration of my major in my college, it will be better ifmy tutor is in the field of engineering .



谈谈郑州（郑大）

Zhengzhou is thecapital city of Henan province. And it is a national transportation hub, knownas China railway heart and Chinese traffic crossroads. It is also one of theeight ancient capitals in China. There are many places of interest there. Forinstance, the Shaolin Temple enjoys international fame. Every year, millions oftourists from all over the world visit it .

Zhengzhou Universityis one of the national “211 project” universities. Through years of greatefforts, it has developed into a comprehensive university. It has a largecampus, which is beautiful beyond expression, especially in spring. The mostpleasant thing is riding a bicycle on campus after class in a sunny day.

How to balance workand study?

From my point of view,study is the top priority for any student, but it does not mean that we shouldstudy all day. Study is the preparation for work after all. I think the mostimportant thing to strike a balance between work and study is, when you are atwork, you could find your weakness and problem, and fix them through study, andyou should always remember what kind of work you want, and study selectively.



你的优缺点（性格，能力，对专业有何作用）

优点一：Personally, I am adetail-oriented girl. I’m cooperative and creative, and have ability ofpractice. When I work on aproject, I don't just want  to meetdeadlines. Rather, I prefer to complete the project well ahead of schedule.

优点二：Personally, I am a patient andoptimistic girl. I always see the bright side of things, and if I am assigned atask, I will be committed to it until it is satisfactorily finished.

缺点一：I find it a bit difficult torefuse others, and that really makes me troublesome sometimes In the future, Iwould try to refuse other decidedly if needed.

缺点二：I feel a bit nervous whenspeaking before a large audience, but it will be better if I’m talking aboutsomething I’m familiar with, so if I am to make a speech in the public, I willmake full preparation. To be honest, I really admire those who speakingeloquently.

12. Tell me about yourfamily

There are four peoplein my family, my parents, my twin sister and me. Both of my parents areworkers. My father is a lovely man, just like a friend of us, but sometimes heis a little strict with us. And my mother is good-tempered, so, when we haveany trouble in life, we turn to her. They always tell me to develop my overallquality in addition to studying hard. My sister is also a senior studentmajoring in aquaculture in ___University. (She is preparing for the civilservice examination now.)During my preparation for coming here, their love andsupport have always been one of my driving forces.



如果对问题不理解

Sorry, but could youplease repeat the question?

To be frank, I don’tknow much about this field, and I wish I can have a chance to learn itsystematically under your instruction.

结束语

That’s all. Thank youagain for giving me this precious opportunity. Wish you a good day.
