* model
- It is evidently illustrated in the photograph that XXXX, XXXX has been a
  heated discussion on the internet recently. Simple as the picture is, it tells
  us XXXX has been greatly influnenced and XX by XXXX.
- To the best of my knowledge, several reasons can be identified to account for
  this phenomenon. To begin with, the government should launch a massive moral
  campaign to educate all citizens and draw up tougher laws to XX and XX. What's
  more, organizations about XX should attach due attention to XXXX. Last but not
  least, the fact that individuals have not realized the significance of XXXX is
  also responsible for this phenomenon.
- Considering all the points discussed, it is highly sensible that we take
  prompt measures to XXXX. Only by enforcing these measures, can we effectively,
  efficiently, and eventually sove the problem.
* model2
- Dear XX,
- I'm XX to hear that XXXX, so it is with the great pleasure I'm writing this
  letter to XXXX.
- On one hand, XXXX; On the other hand / On the contrary, XXXX.
- Thank you for reading my letter, I would like to meet you / receive your reply
  to discuss the details of XX in your convenient time. It's my honor for
  considering XXXX.
- Yours sincerely, Li Ming.
